- name: Deploy to EC2
  hosts: localhost
  connection: local

  tasks:
    - name: Gathering info
      vars:
        ansible_python_interpreter: /usr/local/bin/python3
      ec2_instance_info:
        region: us-east-1
        aws_access_key: ASIAYKFY54BA7YLRLI5T
        aws_secret_key: 6qMHZfru78lVsE8T9x4c2jeT5Z8LT6vWaNknwB3p
        security_token: IQoJb3JpZ2luX2VjEJT//////////wEaCXVzLXdlc3QtMiJGMEQCIANsLnTi2S28kNsstnIhNgMOw5NIWVJwbzTsNOljCxchAiA9a4ZEgHzLrFdk/zopEaDw7NUMrAHGgG/1VffUKRU2YSqtAggdEAAaDDU3MTYxODQ4NDI4OSIMDAPveA9X7piJU8IYKooCuKus5j63yhz0jXN32xwKxLNLCbU4QymqJvRMRCTc8GZquuQCeW/CqVfMKYV6rmUnG0dI3m8Dgi3oz2BP4FnTLYWtX5/t56A9m7m8CAR0bJ6DZlEBF6cyW/WVCS/emOmqsedoiP08lE3wyrYq9MGGKcSpESYXoBSJr58eZe0LutTpuVa20ZNf61ZefdKgZhYtHcjliWFEtdMhCjmOJR9vO0rNls91z8IXuq6kY2JDhQnCRVg55PURbSEbibtsnECv3y4YrnfQPP/74oirhLnW42WgbLXUMAKBsNQZ8woG1y6iKtE3vOoIYx6l3aSFWi4N0WT+NZrBTKmJSHo+TP+7hud4wxsl9l3cY7cw2+fLhAY6ngF6AdHLp/Wy87gwxP9M7I6PZ6d02RBJAHWXOsGqiO3qvCHDqBfHU09N1+RBRwNnoYzO/BZOYcmRYaYn6dUox8WSZAM0/rJ80Q7N4aV4W6VwxYOsU6Kl6F9y5oGw6Y7YWJMasJARKe6xALhRemVDCm4aZZTO3Qj0T28evhkuDKzWREe+xgUXL8MlAgxdvIbUuYSvb2UfEXUZdIWBrjNZtQ==
      register: ec2_info
      
    - name: Lauanch EC2 instance
      ec2:
        instance_type: t2.small
        image: ami-00ddb0e5626798373
        region: us-east-1
        key_name: test1
        vpc_subnet_id: subnet-63b87052
        assign_public_ip: yes
        wait: yes
        count: 1
        group: eshop
        aws_access_key: ASIAYKFY54BA7YLRLI5T
        aws_secret_key: 6qMHZfru78lVsE8T9x4c2jeT5Z8LT6vWaNknwB3p
        security_token: IQoJb3JpZ2luX2VjEJT//////////wEaCXVzLXdlc3QtMiJGMEQCIANsLnTi2S28kNsstnIhNgMOw5NIWVJwbzTsNOljCxchAiA9a4ZEgHzLrFdk/zopEaDw7NUMrAHGgG/1VffUKRU2YSqtAggdEAAaDDU3MTYxODQ4NDI4OSIMDAPveA9X7piJU8IYKooCuKus5j63yhz0jXN32xwKxLNLCbU4QymqJvRMRCTc8GZquuQCeW/CqVfMKYV6rmUnG0dI3m8Dgi3oz2BP4FnTLYWtX5/t56A9m7m8CAR0bJ6DZlEBF6cyW/WVCS/emOmqsedoiP08lE3wyrYq9MGGKcSpESYXoBSJr58eZe0LutTpuVa20ZNf61ZefdKgZhYtHcjliWFEtdMhCjmOJR9vO0rNls91z8IXuq6kY2JDhQnCRVg55PURbSEbibtsnECv3y4YrnfQPP/74oirhLnW42WgbLXUMAKBsNQZ8woG1y6iKtE3vOoIYx6l3aSFWi4N0WT+NZrBTKmJSHo+TP+7hud4wxsl9l3cY7cw2+fLhAY6ngF6AdHLp/Wy87gwxP9M7I6PZ6d02RBJAHWXOsGqiO3qvCHDqBfHU09N1+RBRwNnoYzO/BZOYcmRYaYn6dUox8WSZAM0/rJ80Q7N4aV4W6VwxYOsU6Kl6F9y5oGw6Y7YWJMasJARKe6xALhRemVDCm4aZZTO3Qj0T28evhkuDKzWREe+xgUXL8MlAgxdvIbUuYSvb2UfEXUZdIWBrjNZtQ==
      register: ec2

    - name: Add instance host to group
      add_host: hostname={{ item.public_dns_name }} groupname=launched
      with_items: '{{ec2.instances}}'

    - name: Wait for SSH connection
      wait_for: host={{ item.public_dns_name }} port=22 delay=30 timeout=300 state=started
      with_items: '{{ec2.instances}}'
      
- name: Exterminate
  hosts: localhost
  connection: local

  tasks:
    - name: Exterminate
      ec2:
        region: us-east-1
        state: 'absent'
        instance_ids: '{{ item.instance_id }}'
        aws_access_key: ASIAYKFY54BA7YLRLI5T
        aws_secret_key: 6qMHZfru78lVsE8T9x4c2jeT5Z8LT6vWaNknwB3p
        security_token: IQoJb3JpZ2luX2VjEJT//////////wEaCXVzLXdlc3QtMiJGMEQCIANsLnTi2S28kNsstnIhNgMOw5NIWVJwbzTsNOljCxchAiA9a4ZEgHzLrFdk/zopEaDw7NUMrAHGgG/1VffUKRU2YSqtAggdEAAaDDU3MTYxODQ4NDI4OSIMDAPveA9X7piJU8IYKooCuKus5j63yhz0jXN32xwKxLNLCbU4QymqJvRMRCTc8GZquuQCeW/CqVfMKYV6rmUnG0dI3m8Dgi3oz2BP4FnTLYWtX5/t56A9m7m8CAR0bJ6DZlEBF6cyW/WVCS/emOmqsedoiP08lE3wyrYq9MGGKcSpESYXoBSJr58eZe0LutTpuVa20ZNf61ZefdKgZhYtHcjliWFEtdMhCjmOJR9vO0rNls91z8IXuq6kY2JDhQnCRVg55PURbSEbibtsnECv3y4YrnfQPP/74oirhLnW42WgbLXUMAKBsNQZ8woG1y6iKtE3vOoIYx6l3aSFWi4N0WT+NZrBTKmJSHo+TP+7hud4wxsl9l3cY7cw2+fLhAY6ngF6AdHLp/Wy87gwxP9M7I6PZ6d02RBJAHWXOsGqiO3qvCHDqBfHU09N1+RBRwNnoYzO/BZOYcmRYaYn6dUox8WSZAM0/rJ80Q7N4aV4W6VwxYOsU6Kl6F9y5oGw6Y7YWJMasJARKe6xALhRemVDCm4aZZTO3Qj0T28evhkuDKzWREe+xgUXL8MlAgxdvIbUuYSvb2UfEXUZdIWBrjNZtQ==
   
      loop: "{{ ec2_info.instances }}"
      loop_control:
        label: "{{ item.instance_id }}"
        
- name: Configure EC2
  hosts: launched
  connection: ssh

  tasks:
    - name: Install docker
      apt:
        name: docker.io
        state: present
        update_cache: yes
      become: yes
    - service:
        name: docker
        state: started
        enabled: yes
      become: yes
    - name: Get project files from git
      git:
        repo: 'https://github.com/pirm01/semestralka.git'
        dest: ./app
    - name: Build Docker with eshop
      shell: cd app && docker build -t myeshop:latest .
      become: yes
    - name: Run Docker with eshop
      shell: docker run -p 80:3000 myeshop
      async: 365
      poll: 10
      become: yes
    - wait_for:
      port: 80
